name: expertfinder
channels:
  - conda-forge
dependencies:
  - abseil-cpp=20210324.2
  - absl-py=1.0.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=21.4.0
  - blinker=1.4
  - boto3=1.23.5
  - botocore=1.26.6
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.5.18.1
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.0.0
  - cffi=1.15.0
  - charset-normalizer=2.0.12
  - colorama=0.4.4
  - conda=4.12.0
  - conda-package-handling=1.8.1
  - cryptography=37.0.2
  - cycler=0.11.0
  - dataclasses=0.8
  - dnspython=2.2.1
  - flask=2.1.2
  - fonttools=4.33.3
  - freetype=2.10.4
  - frozenlist=1.3.0
  - gast=0.5.3
  - giflib=5.2.1
  - google-auth=2.6.6
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - greenlet=1.1.2
  - grpc-cpp=1.43.2
  - h5py=3.6.0
  - hdf5=1.12.1
  - huggingface_hub=0.5.1
  - icu=70.1
  - idna=3.3
  - importlib_metadata=4.11.4
  - itsdangerous=2.1.2
  - jbig=2.1
  - jmespath=1.0.0
  - joblib=1.1.0
  - jpeg=9e
  - keras=2.8.0
  - keras-preprocessing=1.1.2
  - kiwisolver=1.4.2
  - krb5=1.19.3
  - lcms2=2.12
  - lerc=3.0
  - libarchive=3.5.2
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.83.1
  - libcxx=14.0.3
  - libdeflate=1.10
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgfortran
  - libgfortran5
  - libiconv=1.16
  - liblapack=3.9.0
  - libmamba=0.24.0
  - libmambapy=0.24.0
  - libnghttp2=1.47.0
  - libopenblas=0.3.20
  - libpng=1.6.37
  - libprotobuf=3.19.4
  - libsolv=0.7.22
  - libssh2=1.10.0
  - libtiff=4.3.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxml2=2.9.14
  - libzlib=1.2.11
  - llvm-openmp=14.0.3
  - lz4-c=1.9.3
  - lzo=2.10
  - mamba=0.24.0
  - markupsafe=2.1.1
  - matplotlib-base=3.5.2
  - multidict=6.0.2
  - munkres=1.1.4
  - mysql-common=8.0.29
  - mysql-connector-python=8.0.29
  - mysql-libs=8.0.29
  - mysqlclient=2.0.3
  - ncurses=6.3
  - ninja=1.11.0
  - numpy=1.22.4
  - oauthlib=3.2.0
  - openjpeg=2.4.0
  - openssl=1.1.1o
  - opt_einsum=3.3.0
  - packaging=21.3
  - pandas=1.4.2
  - patsy=0.5.2
  - pip=22.1.1
  - protobuf=3.19.4
  - pthread-stubs=0.4
  - pyasn1=0.4.8
  - pybind11-abi=4
  - pycosat=0.6.3
  - pycparser=2.21
  - pyjwt=2.4.0
  - pymysql=1.0.2
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.9.12
  - python-dateutil=2.8.2
  - python-flatbuffers=2.0
  - python_abi=3.9
  - pytorch=1.11.0
  - pytz=2022.1
  - pyu2f=0.1.5
  - pyyaml=6.0
  - re2=2022.02.01
  - readline=8.1
  - reproc=14.2.3
  - reproc-cpp=14.2.3
  - requests=2.27.1
  - requests-oauthlib=1.3.1
  - rsa=4.8
  - ruamel_yaml=0.15.80
  - s3transfer=0.5.2
  - scikit-learn=1.1.1
  - scipy=1.8.1
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - sentence-transformers=2.2.0
  - setuptools=62.3.2
  - six=1.16.0
  - sleef=3.5.1
  - snappy=1.1.9
  - sqlalchemy=1.4.37
  - sqlite=3.38.5
  - statsmodels=0.13.2
  - tensorboard=2.8.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.8.0
  - tensorflow-base=2.8.0
  - tensorflow-estimator=2.8.0
  - termcolor=1.1.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - tokenizers=0.12.1
  - toml=0.10.2
  - torchvision=0.9.1
  - tqdm=4.64.0
  - transformers=4.19.2
  - typing-extensions=4.2.0
  - typing_extensions=4.2.0
  - unicodedata2=14.0.0
  - urllib3=1.26.9
  - wheel=0.37.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - yaml-cpp=0.7.0
  - yarl=1.7.2
  - zipp=3.8.0
  - zlib=1.2.11
  - zstd=1.5.2
  - pip:
    - altair==4.2.0
    - appdirs==1.4.4
    - appnope==0.1.3
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.5
    - asynctest==0.13.0
    - atomicwrites==1.4.0
    - backcall==0.2.0
    - backports-entry-points-selectable==1.1.1
    - backports-zoneinfo==0.2.1
    - beautifulsoup4==4.11.1
    - black==21.7b0
    - bleach==5.0.0
    - blis==0.7.7
    - brotli==1.0.9
    - catalogue==2.0.7
    - certifi==2021.10.8
    - click==8.0.4
    - cymem==2.0.6
    - cython==0.29.23
    - dash==2.3.1
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - datasets==1.9.0
    - debugpy==1.6.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dill==0.3.4
    - distlib==0.3.4
    - docker==5.0.0
    - entrypoints==0.4
    - et-xmlfile==1.1.0
    - executing==0.8.3
    - fastjsonschema==2.15.3
    - filelock==3.6.0
    - flask-compress==1.12
    - flask-mysqldb==1.0.1
    - flask-paginate==2022.1.8
    - fsspec==2022.3.0
    - gensim==4.2.0
    - gitdb==4.0.9
    - gitpython==3.1.27
    - googledrivedownloader==0.4
    - grpcio==1.44.0
    - huggingface-hub==0.0.19
    - importlib-metadata==4.11.3
    - importlib-resources==5.7.1
    - iniconfig==1.1.1
    - ipykernel==6.13.0
    - ipython==8.3.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.0
    - jedi==0.18.1
    - jellyfish==0.9.0
    - jinja2==3.1.1
    - jsons==1.6.1
    - jsonschema==4.4.0
    - jupyter-client==7.2.2
    - jupyter-core==4.10.0
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==1.1.0
    - langcodes==3.3.0
    - libclang==13.0.0
    - lxml==4.8.0
    - markdown==3.3.6
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - multiprocess==0.70.12.2
    - murmurhash==1.0.6
    - mypy-extensions==0.4.3
    - nbclient==0.6.0
    - nbconvert==6.5.0
    - nbformat==5.3.0
    - nest-asyncio==1.5.5
    - networkx==2.8.2
    - nltk==3.7
    - notebook==6.4.11
    - openpyxl==3.0.9
    - overrides==3.1.0
    - pandocfilters==1.5.0
    - parameterized==0.8.1
    - parso==0.8.3
    - pathspec==0.9.0
    - pathy==0.6.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.1.0
    - plac==1.3.5
    - platformdirs==2.5.2
    - plotly==5.7.0
    - pluggy==0.13.1
    - portalocker==2.4.0
    - preshed==3.0.6
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.29
    - psutil==5.9.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py==1.11.0
    - pyarrow==7.0.0
    - pyasn1-modules==0.2.8
    - pydantic==1.8.2
    - pydeck==0.7.1
    - pygments==2.11.2
    - pympler==1.0.1
    - pyparsing==3.0.8
    - pyrsistent==0.18.1
    - pytest==6.2.4
    - pytz-deprecation-shim==0.1.0.post0
    - pyzmq==22.3.0
    - regex==2022.3.15
    - repro==0.1.1
    - responses==0.18.0
    - rouge==1.0.1
    - rouge-score==0.0.4
    - sacrebleu==2.0.0
    - sacremoses==0.0.49
    - sacrerouge==0.2.5
    - segtok==1.5.11
    - semver==2.13.0
    - send2trash==1.8.0
    - sentencepiece==0.1.96
    - setuptools-scm==6.4.2
    - sklearn==0.0
    - smart-open==5.2.1
    - smmap==5.0.0
    - soupsieve==2.3.2.post1
    - spacy==3.3.0
    - spacy-legacy==3.0.9
    - spacy-loggers==1.0.2
    - srsly==2.4.3
    - stack-data==0.2.0
    - streamlit==1.8.1
    - style==1.1.0
    - tabulate==0.8.9
    - tenacity==8.0.1
    - terminado==0.15.0
    - thinc==8.0.15
    - tinycss2==1.1.1
    - tomli==1.2.3
    - toolz==0.11.2
    - torch==1.10.0
    - tornado==6.1
    - traitlets==5.1.1
    - typed-ast==1.5.3
    - typer==0.4.1
    - typing-utils==0.1.0
    - typish==1.9.3
    - tzdata==2022.1
    - tzlocal==4.2
    - update==0.0.1
    - validators==0.19.0
    - wasabi==0.9.1
    - watchdog==2.1.7
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.3.2
    - werkzeug==2.1.1
    - widgetsnbextension==3.6.0
    - wordcloud==1.8.1
    - wrapt==1.14.0
    - xxhash==3.0.0
    - yake==0.4.8
